routes.py
from flask import Blueprint, render_template, url_for, request, redirect, session, jsonify, flash, current_app
from flask_jwt_extended import create_access_token
from flask_mail import Mail
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_user, login_required, logout_user, current_user
from functools import wraps
from datetime import datetime, timedelta
import smtplib, requests, re
from email.mime.text import MIMEText
# from flask_socketio import SocketIO, emit
from models import db, User, Authority, Dashboard, UserDashboardAccess, Passwordrequests, Usernamerequests

routes = Blueprint('routes', __name__)
mail = Mail()
login_manager = None

def init_login_manager(lm):
    global login_manager
    login_manager = lm
    @login_manager.user_loader
    def load_user(user_id):
        return User.query.get(int(user_id))

@routes.record
def record(state):
    app = state.app
    mail.init_app(app)
    routes.app = app

# 사용자 권한과 대시보드 접근 권한을 가져오는 함수
def get_user_permissions(user):
    user_authorities = Authority.query.filter_by(user_id=user.id).all()
    permissions = [authority.authority_name for authority in user_authorities]
    return permissions

def get_user_dashboard_names(user):
    user_dashboard_access = UserDashboardAccess.query.filter_by(user_id=user.id).all()
    dashboard_names = [Dashboard.query.get(access.dashboard_id).dashboard_name for access in user_dashboard_access]
    return dashboard_names

def get_user_dashboard_ids(user):
    if user is None:
        return []
    user_dashboard_access = UserDashboardAccess.query.filter_by(user_id=user.id).all()
    dashboard_ids = [access.dashboard_id for access in user_dashboard_access]
    return dashboard_ids

# 비밀번호 해싱 함수
def hash_password(password):
    return generate_password_hash(password, method='pbkdf2:sha256')

def get_user_login_attempts(user):
    return user.login_attempts

def send_email(subject, from_email, to_emails, text_body):
    msg = MIMEText(text_body)
    msg['Subject'] = subject
    msg['From'] = from_email
    msg['To'] = ', '.join(to_emails)

    try:
        with smtplib.SMTP('smtp.gmail.com', 587) as smtp:
            smtp.starttls()
            smtp.login('kyeongjun.lee@kwinternational.com', 'wzge aend smth rpmb')
            smtp.send_message(msg)
        return True
    except Exception as e:
        print(f"Error sending email: {e}", e)
        return False
    
def send_email_with_mailjet(subject, from_email, to_emails, text_body):
    api_key = 'd096acb42974123d1c97d63a259abf48'
    api_secret = 'f4f900f7f35375b3c271d9c852e237d1'
    url = 'https://api.mailjet.com/v3.1/send'
    data = {
        'Messages': [
            {
                'From': {
                    'Email': from_email,
                    'Name': 'KWI BPO Web Support'
                },
                'To': [
                    {
                        'Email': email,
                        'Name': 'Support Team'
                    } for email in to_emails
                ],
                'Subject': subject,
                'TextPart': text_body
            }
        ]
    }
    response = requests.post(url, auth=(api_key, api_secret), json=data)
    if response.status_code == 200:
        return True, None
    else:
        return False, f"Error sending email with Mailjet: {response.status_code}, {response.text}"

# 마스터 권한 확인 데코레이터
def master_required(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        if not current_user.is_authenticated:
            return redirect(url_for('routes.login'))
        permissions = get_user_permissions(current_user)
        if 'master' not in permissions:
            flash('Access denied. Master permission required.', 'error')
            logout_user()
            return redirect(url_for('routes.index'))
        return f(*args, **kwargs)
    return decorated_function

# 로그인된 사용자가 로그인 페이지와 인덱스 페이지에 접근할 수 없도록 설정
@routes.before_request
def restrict_authenticated_users():
    if current_user.is_authenticated:
        # 세션 타임아웃 확인
        now = datetime.now()
        if 'last_activity' in session:
            last_activity = session['last_activity']
            # 시간대 정보를 제거하여 naive datetime으로 변환
            last_activity = last_activity.replace(tzinfo=None)
            if (now - last_activity) > timedelta(minutes=10):
                logout_user()
                flash('Your session has expired due to inactivity.', 'info')
                return redirect(url_for('routes.login'))
        session['last_activity'] = now  # 활동 시간 업데이트

        if request.endpoint in ['routes.login', 'routes.index']:
            return redirect(url_for('routes.welcome'))

# 세션 만료 확인
@routes.before_request
def make_session_permanent():
    session.permanent = True
    session.modified = True

# 라우트 정의
# main
@routes.route('/', methods=['GET'])
def index():
    return render_template('home/index.html')

# about
@routes.route('/about', methods=['GET'])
def about():
    return render_template('company/about.html')

# login
@routes.route('/login', methods=['GET', 'POST'])
def login():
    user = None
    last_attempt_time = datetime.now().isoformat()  # ISO 형식으로 변환
    remaining_time_seconds = 0  # 초 단위로 초기화

    # 이미 인증된 사용자라면 환영 페이지로 리디렉션
    if current_user.is_authenticated:
        return redirect(url_for('routes.welcome'))

    # POST 요청 처리
    if request.method == 'POST':
        username = request.form['username']  # 사용자 이름 가져오기
        password = request.form['password']  # 비밀번호 가져오기

        user = User.query.filter_by(username=username).first()  # 사용자 데이터베이스에서 사용자 검색
        
        if user:
            last_attempt_time = user.last_attempt_time  # 마지막 시도 시간 가져오기
            last_attempt_time = last_attempt_time if isinstance(last_attempt_time, datetime) else datetime.fromisoformat(last_attempt_time)
            time_since_last_attempt = datetime.now() - (last_attempt_time if last_attempt_time else datetime.now() - timedelta(minutes=15))
            
            # 남은 시간 계산
            if user.login_attempts >= 5 and time_since_last_attempt < timedelta(minutes=15):
                remaining_time = timedelta(minutes=15) - time_since_last_attempt
                remaining_time_seconds = int(remaining_time.total_seconds())  # 초 단위로 변환

                # 남은 시간이 있을 경우 플래시 메시지 추가
                if remaining_time_seconds > 0:
                    if remaining_time_seconds > 60:
                        minutes = remaining_time_seconds // 60
                        seconds = remaining_time_seconds % 60
                        flash(f'No attempts remaining. Please try again after {minutes} minutes and {seconds} seconds.', 'error')
                    else:
                        flash(f'No attempts remaining. Please try again after {remaining_time_seconds} seconds.', 'error')
                    return render_template('auth/login.html', remaining_time=remaining_time_seconds, last_attempt_time=last_attempt_time)

            elif time_since_last_attempt >= timedelta(minutes=15):
                # 15분이 지나면 로그인 시도 횟수를 초기화
                user.login_attempts = 0
                user.last_attempt_time = datetime.now()
                db.session.commit()

            # 비밀번호 확인
            if check_password_hash(user.password, password):
                user.login_attempts = 0  # 로그인 성공 시 시도 횟수 초기화
                user.stay_signed_in = True
                user.last_attempt_time = datetime.now()
                db.session.commit()
                
                login_user(user)
                access_token = create_access_token(identity=username)
                session['user_id'] = user.id
                session['access_token'] = access_token
                session.pop('error_count', None)
                return redirect(url_for('routes.welcome'))
            else:
                # 비밀번호가 틀린 경우
                user.login_attempts += 1
                user.stay_signed_in = False
                user.last_attempt_time = datetime.now()
                db.session.commit()
        else:
            flash('The ID or password you entered is incorrect.', 'error')
            return redirect(url_for('routes.login'))

        # 로그인 시도 횟수에 따른 오류 메시지 표시
        if user.login_attempts >= 5:
            # 남은 시간이 있을 때 리다이렉트
            if remaining_time_seconds > 0:
                return redirect(url_for('routes.login'))  # 남은 시간이 있을 때 리다이렉트
        else:
            flash(f'The ID or password you entered is incorrect. Attempts remaining: {5 - user.login_attempts}', 'error')

        return redirect(url_for('routes.login'))

    return render_template('auth/login.html', remaining_time=remaining_time_seconds, last_attempt_time=last_attempt_time)

# forgot_password        
@routes.route('/forgot_password', methods=['GET', 'POST'])
def forgot_password():
    if request.method == 'POST':
        data = request.get_json()
        username = data.get('username')
        firstname = data.get('first_name')
        lastname = data.get('last_name')
        email = data.get('email')
        confirmemail = data.get('confirmemail')
        department = data.get('department')

        user = get_user_by_name(firstname, lastname)
        if user:
            if not email:
                return jsonify({'success': False, 'error': 'Please enter an email address.'}), 400
            elif email != confirmemail:
                return jsonify({'success': False, 'error': 'Please check and confirm your email.'}), 400
            elif not isinstance(email, str) or not re.match(r'^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$', email):
                return jsonify({'success': False, 'error': 'Please enter a valid email address (e.g., name@example.com).'}), 400

            user = save_forogotpass_to_db(username, firstname, lastname, email, department)

            smtp_server = "in-v3.mailjet.com"
            smtp_port = 587
            smtp_use_tls = "optional"

templates/company/about.html
<!doctype html>
<html class="no-js" lang="EN">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="description" content="KW Contact Center offers comprehensive and fully tailored services that are specific to your e-commerce business.">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="icon" type="image/x-icon" href="{{ url_for('static', filename='images/favicon.ico') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}" type="text/css">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/animate.css') }}" type="text/css">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/font-awesome.min.css') }}" type="text/css">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/about.css') }}" type="text/css">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}" type="text/css">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/home.css') }}" type="text/css">
    
    <title>KW | About Us</title>
</head>

<body>
    <!--[if lt IE 8]>
        <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
    <![endif]-->

    <header class="header-social">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <!-- <a href="https://www.facebook.com/KWInternational97/"><i class="fa fa-facebook" aria-hidden="true"></i></a>
                    <a href="https://twitter.com/KW_Intl"><i class="fa fa-twitter" aria-hidden="true"></i></a>
                    <a href="https://www.instagram.com/kwinternational/"><i class="fa fa-instagram" aria-hidden="true"></i></a>  -->
                </div>
            </div>
        </div>
    </header>

    <nav class="navbar navbar-default navbar-kw-bpo navbar-fixed-top">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <i class="fa fa-bars" aria-hidden="true"></i> Menu
                </button>
                <a class="navbar-brand" href="{{ url_for('routes.index') }}">
                    <img src="{{ url_for('static', filename='img/kw-logo.png') }}" class="img-responsive" width="100px" alt="KW Logo.">
                </a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right navbar-right-kw">
                    <!-- <li><a data-scroll href="#section-services">Services</a></li> -->
                    <!-- <li><a data-scroll href="#section-solutions">Our Advantage</a></li> -->
                    <!-- <li><a href="/templates/contact.aspx">Contact</a></li> -->
                    <li><a href="{{ url_for('routes.index') }}">Home</a></li>
                    <li><a href="{{ url_for('routes.about') }}">About Us</a></li>
                    <li><a href="{{ url_for('routes.login') }}">Login</a></li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <section class="section-banner">
        <div class="container">
            <div class="banner-context">
                <h1>About Us</h1>
            </div>
        </div>
    </section>
    <section class="section-breadcrumb">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="breadcrumb-wrapper">
                        Home / About Us
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section class="section-overview">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="overview-wrapper text-center">
                        <!--
                        <div class="ceo-img">
                            <img src="{{ url_for('static', filename='img/exp_leadership_man.png') }}" class="img-responsive img-circle" alt="CEO">
                        </div>
-->
                        <div>
                            <h3>CEO Greetings</h3>
                        </div>
                        <div class="overview-content">
                            <p>Over the years, KW has developed an unparalleled array of services that are customized and dedicated to each customer. As a mid-sized logistics company, our strengths really show in tailored services and personal attention that many large-scale wholesale logistics providers lack.</p>
                            <p>We believe KW is in the best position to provide tailored services. We have a simple and quick decision-making process, yet sufficient resources to effect changes quickly. We are ready to customize our services and restructure our operations around yours.</p>
                            <p>We take seriously learning the specific goals and needs of our customers in order to build a successful operation model. We do not simply want to sell service products we already have. With each of our customers, we are determined to build a team of experts to develop detailed plans for system integration and implementation, operation review metrics, nationwide service network, employee training, and other service aspects. Our service capability is a continuing process.</p>
                            <p><strong>We see our future in our customer's future. Our success in our customer's success.</strong></p>
                        </div>
                        <div class="signature">
                            <img src="{{ url_for('static', filename='img/signature.png') }}" class="img-responsive" alt="CEO Signature">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <footer>
        <div class="container">
            <div class="row">
                <div class="col-md-2">
                    <div class="footer-logo">
                        <img src="{{ url_for('static', filename='img/kw-logo-white.png') }}" class="img-responsive" alt="Footer logo.">
                    </div>
                </div>
                <div class="col-md-8">
                    <ul class="footer-nav">
                        <!--
                        <li><a data-scroll href="index.html#section-solutions">Our Advantage</a></li>
                        <li><a data-scroll href="index.html#section-services">Services</a></li>
                        <li><a href="contact.aspx">Contact</a></li>
                        <li><a href="about.html">About Us</a></li>
                        <li><a href="contact.aspx" class="btn-quote">Request Quote</a></li>
                        -->
                    </ul>
                </div>
                <div class="col-md-2">
                    <div class="footer-social">
                        <!--
                        <a href="https://www.facebook.com/KWInternational97/"><i class="fa fa-facebook" aria-hidden="true"></i></a>
                        <a href="https://twitter.com/KW_Intl"><i class="fa fa-twitter" aria-hidden="true"></i></a>
                        <a href="https://www.instagram.com/kwinternational/"><i class="fa fa-instagram" aria-hidden="true"></i></a>
                        -->
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <p class="text-center">
                        KW International Inc © 2011 All rights reserved.
                    </p>
                </div>
            </div>
        </div>
    </footer>

    <script src="{{ url_for('static', filename='js/jquery-1.12.0.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/modernizr-2.8.3.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/smooth-scroll.js') }}"></script>

    <script>
        $(document).ready(function() {

            smoothScroll.init();

            //Navigation Section
            $(window).scroll(function() {
                if ($(this).scrollTop() >= 50) {
                    $('.navbar-kw-bpo').addClass('sticky');
                } else {
                    $('.navbar-kw-bpo').removeClass('sticky');
                }
            });
        });
    </script>

    <script>
        (function(i, s, o, g, r, a, m) {
            i['GoogleAnalyticsObject'] = r;
            i[r] = i[r] || function() {
                (i[r].q = i[r].q || []).push(arguments)
            }, i[r].l = 1 * new Date();
            a = s.createElement(o),
                m = s.getElementsByTagName(o)[0];
            a.async = 1;
            a.src = g;
            m.parentNode.insertBefore(a, m)
        })(window, document, 'script', 'https://www.google-analytics.com/analytics.js', 'ga');

        ga('create', 'UA-104736640-1', 'auto');
        ga('send', 'pageview');
    </script>
</body>

</html>